-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 11:15:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auvodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auvodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auvodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `auvodb` ;

-- -----------------------------------------------------
-- Table `auvodb`.`segments_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`segments_auvo` (
  `segmentId` INT NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `registrationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`segmentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_auvo` (
  `customerId` INT NOT NULL,
  `externalId` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cpfCnpj` VARCHAR(50) NULL DEFAULT NULL,
  `manager` VARCHAR(100) NULL DEFAULT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `addressComplement` TEXT NULL DEFAULT NULL,
  `latitude` VARCHAR(30) NULL DEFAULT NULL,
  `longitude` VARCHAR(30) NULL DEFAULT NULL,
  `uriAttachments` TEXT NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  `dateLastUpdate` DATETIME NULL DEFAULT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  `segmentId` INT NOT NULL,
  PRIMARY KEY (`customerId`),
  INDEX `fk_customers_segments1_idx` (`segmentId` ASC) VISIBLE,
  CONSTRAINT `fk_customers_segments1`
    FOREIGN KEY (`segmentId`)
    REFERENCES `auvodb`.`segments_auvo` (`segmentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_contacts` (
  `contactId` INT NOT NULL,
  `customerId` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `contactJobPosition` VARCHAR(45) NULL DEFAULT NULL,
  `contactEmail` VARCHAR(45) NULL DEFAULT NULL,
  `contactPhone` VARCHAR(45) NULL DEFAULT NULL,
  `contactName` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_contacts_customers1_idx` (`customerId` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_customers1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_emails` (
  `customerId` INT NOT NULL,
  `customer_email` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_emails_customers1_idx` (`customerId` ASC) VISIBLE,
  CONSTRAINT `fk_emails_customers1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`groups_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`groups_auvo` (
  `groupId` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`groupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_groups` (
  `customerId` INT NOT NULL,
  `groupId` INT NOT NULL,
  PRIMARY KEY (`customerId`, `groupId`),
  INDEX `fk_customer_has_groups_groups1_idx` (`groupId` ASC) VISIBLE,
  INDEX `fk_customer_has_groups_customer1_idx` (`customerId` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_groups_customer1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`),
  CONSTRAINT `fk_customer_has_groups_groups1`
    FOREIGN KEY (`groupId`)
    REFERENCES `auvodb`.`groups_auvo` (`groupId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`userstypes_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`userstypes_auvo` (
  `userTypeId` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`userTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`users_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`users_auvo` (
  `userId` INT NOT NULL,
  `externalId` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `login` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `jobPosition` VARCHAR(100) NULL DEFAULT NULL,
  `userType` INT NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `basePoint` POINT NULL DEFAULT NULL,
  `registrationDate` DATETIME NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_users_usersTypes_idx` (`userType` ASC) VISIBLE,
  CONSTRAINT `fk_users_usersTypes`
    FOREIGN KEY (`userType`)
    REFERENCES `auvodb`.`userstypes_auvo` (`userTypeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_managers` (
  `userId` INT NOT NULL,
  `customerId` INT NOT NULL,
  INDEX `fk_users_has_customer_customer1_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_users_has_customer_users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_customer_customer1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`),
  CONSTRAINT `fk_users_has_customer_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `auvodb`.`users_auvo` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `auvodb`.`customers_uriattachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`customers_uriattachments` (
  `uriAttachmentsId` INT NOT NULL AUTO_INCREMENT,
  `urls` TEXT NULL DEFAULT NULL,
  `customerId` INT NOT NULL,
  PRIMARY KEY (`uriAttachmentsId`),
  INDEX `fk_uriAttachments_customers1_idx` (`customerId` ASC) VISIBLE,
  CONSTRAINT `fk_uriAttachments_customers1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`))
ENGINE = InnoDB
AUTO_INCREMENT = 145
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`glpi_tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`glpi_tickets` (
  `externalId` INT NOT NULL,
  `customerName` VARCHAR(100) NULL DEFAULT NULL,
  `ticketTitle` VARCHAR(100) NULL DEFAULT NULL,
  `ticket_description` TEXT NULL DEFAULT NULL,
  `openDate` DATETIME NULL DEFAULT NULL,
  `ticketStatus` INT NULL DEFAULT NULL,
  `lastAtualization` DATETIME NULL DEFAULT NULL,
  `categorySla` VARCHAR(100) NULL DEFAULT NULL,
  `slaTime` VARCHAR(50) NULL DEFAULT NULL,
  `slaStatus` INT NULL DEFAULT NULL,
  `reasonForPause` VARCHAR(100) NULL DEFAULT NULL,
  `atribuiedUserId` INT NULL DEFAULT NULL,
  UNIQUE INDEX `externalId` (`externalId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`glpi_typealerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`glpi_typealerts` (
  `typeId` INT NOT NULL,
  `notification` TEXT NULL DEFAULT NULL,
  `previousNotificationType` VARCHAR(50) NULL DEFAULT NULL,
  `actualNotificationType` VARCHAR(50) NULL DEFAULT NULL,
  `alertSeverty` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`typeId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`questionnaires_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`questionnaires_auvo` (
  `questionaryId` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `header` TEXT NULL DEFAULT NULL,
  `footer` TEXT NULL DEFAULT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`questionaryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`questionnairesquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`questionnairesquestions` (
  `questionId` INT NOT NULL,
  `questionnaireId` INT NOT NULL,
  `answerType` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `subtitle` TEXT NULL DEFAULT NULL,
  `requiredAnswer` TINYINT NOT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`questionId`),
  INDEX `fk_questionnairesQuestions_questionnaires_auvo1_idx` (`questionnaireId` ASC) VISIBLE,
  CONSTRAINT `fk_questionnairesQuestions_questionnaires_auvo1`
    FOREIGN KEY (`questionnaireId`)
    REFERENCES `auvodb`.`questionnaires_auvo` (`questionaryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`questionnairesanswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`questionnairesanswers` (
  `questionnairesAnswersId` INT NOT NULL,
  `questionnairesQuestionsId` INT NOT NULL,
  `questionId` INT NULL DEFAULT NULL,
  `replyId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`questionnairesAnswersId`, `questionnairesQuestionsId`),
  INDEX `fk_questionnairesAnswers_questionnairesQuestions1_idx` (`questionnairesQuestionsId` ASC) VISIBLE,
  CONSTRAINT `fk_questionnairesAnswers_questionnairesQuestions1`
    FOREIGN KEY (`questionnairesQuestionsId`)
    REFERENCES `auvodb`.`questionnairesquestions` (`questionId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`questionnariesreplies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`questionnariesreplies` (
  `idquestionnariesReplies` INT NOT NULL,
  `questionnairesAnswersId` INT NOT NULL,
  `replyId` INT NULL DEFAULT NULL,
  `relpy` TEXT NULL DEFAULT NULL,
  `replyDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idquestionnariesReplies`, `questionnairesAnswersId`),
  INDEX `fk_questionnariesReplies_questionnairesAnswers1_idx` (`questionnairesAnswersId` ASC) VISIBLE,
  CONSTRAINT `fk_questionnariesReplies_questionnairesAnswers1`
    FOREIGN KEY (`questionnairesAnswersId`)
    REFERENCES `auvodb`.`questionnairesanswers` (`questionnairesAnswersId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tasks_types_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tasks_types_auvo` (
  `tasksTypesId` INT NOT NULL,
  `userCreatorId` INT NOT NULL,
  `standardQuestionnaireId` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `creationDate` DATETIME NULL DEFAULT NULL,
  `standardTime` TIME NULL DEFAULT NULL,
  `toleranceTime` TIME NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`tasksTypesId`, `userCreatorId`, `standardQuestionnaireId`),
  INDEX `fk_tasks_types_auvo_users_auvo1_idx` (`userCreatorId` ASC) VISIBLE,
  INDEX `fk_tasks_types_auvo_questionnaires_auvo1_idx` (`standardQuestionnaireId` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_types_auvo_questionnaires_auvo1`
    FOREIGN KEY (`standardQuestionnaireId`)
    REFERENCES `auvodb`.`questionnaires_auvo` (`questionaryId`),
  CONSTRAINT `fk_tasks_types_auvo_users_auvo1`
    FOREIGN KEY (`userCreatorId`)
    REFERENCES `auvodb`.`users_auvo` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tasks_types_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tasks_types_requirements` (
  `taskTypeRequirementId` INT NOT NULL AUTO_INCREMENT,
  `tasksTypesId` INT NOT NULL,
  `fillReport` VARCHAR(100) NULL DEFAULT NULL,
  `getSignature` VARCHAR(100) NULL DEFAULT NULL,
  `minimumNumberOfPhotos` INT NULL DEFAULT NULL,
  `requiredAnswer` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`taskTypeRequirementId`, `tasksTypesId`),
  UNIQUE INDEX `tasksTypesId_UNIQUE` (`tasksTypesId` ASC) VISIBLE,
  INDEX `fk_tasks_types_requirements_tasks_types_auvo1_idx` (`tasksTypesId` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_types_requirements_tasks_types_auvo1`
    FOREIGN KEY (`tasksTypesId`)
    REFERENCES `auvodb`.`tasks_types_auvo` (`tasksTypesId`))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`requiredquestionnaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`requiredquestionnaires` (
  `questionnaireId` INT NOT NULL,
  `TaskTypesRequirementId` INT NOT NULL,
  PRIMARY KEY (`questionnaireId`, `TaskTypesRequirementId`),
  INDEX `fk_questionnaires_auvo_has_tasks_types_requirements_tasks_t_idx` (`TaskTypesRequirementId` ASC) VISIBLE,
  INDEX `fk_questionnaires_auvo_has_tasks_types_requirements_questio_idx` (`questionnaireId` ASC) VISIBLE,
  CONSTRAINT `fk_questionnaires_auvo_has_tasks_types_requirements_questionn1`
    FOREIGN KEY (`questionnaireId`)
    REFERENCES `auvodb`.`questionnaires_auvo` (`questionaryId`),
  CONSTRAINT `fk_questionnaires_auvo_has_tasks_types_requirements_tasks_typ1`
    FOREIGN KEY (`TaskTypesRequirementId`)
    REFERENCES `auvodb`.`tasks_types_requirements` (`taskTypeRequirementId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tasks_prioritys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tasks_prioritys` (
  `taskPriorityId` INT NOT NULL,
  `priorityDescription` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`taskPriorityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tasks_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tasks_status` (
  `taskStatusId` INT NOT NULL,
  `statusDescriptions` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`taskStatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tasks_auvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tasks_auvo` (
  `taskId` INT NOT NULL,
  `userFromId` INT NOT NULL,
  `userToId` INT NOT NULL,
  `taskPriorityId` INT NOT NULL,
  `customerId` INT NOT NULL,
  `taskStatusID` INT NOT NULL,
  `tasksTypesId` INT NOT NULL,
  `externalId` INT NULL DEFAULT NULL,
  `taskDate` DATETIME NULL DEFAULT NULL,
  `taskCreationDate` DATETIME NULL DEFAULT NULL,
  `orientation` TEXT NULL DEFAULT NULL,
  `deliveredOnSmarthPhone` VARCHAR(45) NULL DEFAULT NULL,
  `deliveredDate` DATETIME NULL DEFAULT NULL,
  `finished` TINYINT NULL DEFAULT NULL,
  `report` TEXT NULL DEFAULT NULL,
  `visualized` TINYINT NULL DEFAULT NULL,
  `visualizedDate` DATETIME NULL DEFAULT NULL,
  `checkIn` TINYINT NULL DEFAULT NULL,
  `checkInDate` DATETIME NULL DEFAULT NULL,
  `checkOut` TINYINT NULL DEFAULT NULL,
  `checkOutDate` DATETIME NULL DEFAULT NULL,
  `checkinType` INT NULL DEFAULT NULL,
  `inputedKm` DECIMAL(10,2) NULL DEFAULT NULL,
  `adoptedKm` DECIMAL(10,2) NULL DEFAULT NULL,
  `attachmentsId` INT NULL DEFAULT NULL,
  `questionnairesId` INT NULL DEFAULT NULL,
  `signatureUrl` TEXT NULL DEFAULT NULL,
  `checkInDistance` DECIMAL(10,2) NULL DEFAULT NULL,
  `checkOutDistance` DECIMAL(10,2) NULL DEFAULT NULL,
  `taskUrl` TEXT NULL DEFAULT NULL,
  `pendency` TEXT NULL DEFAULT NULL,
  `dateLastUpdate` DATETIME NULL DEFAULT NULL,
  `displacementStart` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`taskId`),
  INDEX `fk_tasks_auvo_users_auvo1_idx` (`userFromId` ASC) VISIBLE,
  INDEX `fk_tasks_auvo_users_auvo2_idx` (`userToId` ASC) VISIBLE,
  INDEX `fk_tasks_auvo_customers_auvo1_idx` (`customerId` ASC) VISIBLE,
  INDEX `fk_tasks_auvo_tasks_Status1_idx` (`taskStatusID` ASC) VISIBLE,
  INDEX `fk_tasks_auvo_tasks_prioritys1_idx` (`taskPriorityId` ASC) VISIBLE,
  INDEX `fk_tasks_auvo_tasks_types_auvo2_idx` (`tasksTypesId` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_auvo_customers_auvo1`
    FOREIGN KEY (`customerId`)
    REFERENCES `auvodb`.`customers_auvo` (`customerId`),
  CONSTRAINT `fk_tasks_auvo_tasks_prioritys1`
    FOREIGN KEY (`taskPriorityId`)
    REFERENCES `auvodb`.`tasks_prioritys` (`taskPriorityId`),
  CONSTRAINT `fk_tasks_auvo_tasks_Status1`
    FOREIGN KEY (`taskStatusID`)
    REFERENCES `auvodb`.`tasks_status` (`taskStatusId`),
  CONSTRAINT `fk_tasks_auvo_tasks_types_auvo2`
    FOREIGN KEY (`tasksTypesId`)
    REFERENCES `auvodb`.`tasks_types_auvo` (`tasksTypesId`),
  CONSTRAINT `fk_tasks_auvo_users_auvo1`
    FOREIGN KEY (`userFromId`)
    REFERENCES `auvodb`.`users_auvo` (`userId`),
  CONSTRAINT `fk_tasks_auvo_users_auvo2`
    FOREIGN KEY (`userToId`)
    REFERENCES `auvodb`.`users_auvo` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auvodb`.`tickets_alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auvodb`.`tickets_alerts` (
  `alertId` INT NOT NULL AUTO_INCREMENT,
  `glpi_typeAlertId` INT NULL DEFAULT NULL,
  `glpi_ticketId` INT NULL DEFAULT NULL,
  `checked` TINYINT NULL DEFAULT '0',
  `justifiedText` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`alertId`),
  INDEX `glpi_typeAlertId` (`glpi_typeAlertId` ASC) VISIBLE,
  CONSTRAINT `tickets_alerts_ibfk_1`
    FOREIGN KEY (`glpi_typeAlertId`)
    REFERENCES `auvodb`.`glpi_typealerts` (`typeId`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `auvodb`;

DELIMITER $$
USE `auvodb`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `auvodb`.`tickets_alerts_automatic_update`
AFTER UPDATE ON `auvodb`.`glpi_tickets`
FOR EACH ROW
begin
if new.ticketStatus = 6 then
update tickets_alerts
SET checked = 1,
justifiedText = "Chamado finalizado, justificado pelo sistema"
where glpi_ticketId = new.externalId;
end if;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
